### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ruipatornilho** [lucidworks/hadoop-solr#12]
I have 100 errors derived by  error: package com.lucidworks.hadoop.io does not exist

I did the steps exactly like you have in README 
please help

Thanks

**Comment by acesar** [comment]
@ruipatornilho Did you get the error building the jar? or executing it?

**Comment by ruipatornilho** [comment]
it was when i build the jar but i already fix  it
The builld error was because git submodules update dont have permissions to access another repository that where you clone hadoop common 

another question is i have an error 
in grok prints Error cache grok null
do you know what that means
Thanks in advance

**Comment by acesar** [comment]
@ruipatornilho please open a new ticket with the new question.
You should post the septs to reproduce the error (also post the stack trace).
