### ISSUE TITLE
Retrieve input name or input path

### ISSUE THREAD

**Issue by spyrosAv** [lucidworks/hadoop-solr#16]
I'm searching through 2 txt files for words. Is there any way to retrieve as result except the row ,with the word in, of the file and its name?   
Currently i am running the project like this : 
```
 hadoop jar solr-hadoop-job-2.2.5.jar 
    com.lucidworks.hadoop.ingest.IngestJob  
    -Dlww.commit.on.close=true -DcsvDelimiter= 
   -cls com.lucidworks.hadoop.ingest.CSVIngestMapper -c spyros1  
    - i  /usr/local/hadoop/input 
    -of com.lucidworks.hadoop.io.LWMapRedOutputFormat 
    -s http://127.0.1.1:8983/solr
```
Is somehow possible make it?

**Comment by ctargett** [comment]
I'm not sure I understand what you would like to see. Are you saying you just want to see the row number and file name?

**Comment by spyrosAv** [comment]
@ctargett Yes i want to see also the file's name that the results came from.

**Comment by acesar** [comment]
> I'm searching through 2 txt files for words.
you are ingesting the 2 txt files and then doing a query Solr to do the search, correct? 

are you searching for a specify word?

You can try the `RegexIngestMapper`. 
* The `com.lucidworks.hadoop.ingest.RegexIngestMapper.regex` argument is a regex, in the example "\\w+"`,  will add every `word` as a field.

```
   hadoop jar solr-hadoop-job-2.2.5.jar com.lucidworks.hadoop.ingest.IngestJob  -Dlww.commit.on.close=true -Dcom.lucidworks.hadoop.ingest.RegexIngestMapper.regex="\\w+" -Dcom.lucidworks.hadoop.ingest.RegexIngestMapper.groups_to_fields=0=match_s  -cls com.lucidworks.hadoop.ingest.RegexIngestMapper  -c collection1 -i /path/* -zk 127.0.0.1:2181/solr -of com.lucidworks.hadoop.io.LWMapRedOutputFormat 
``` 

Result the Solr document:
```
id=/path/file-name.txt-<ROW>, match_s=[wordA, wordB, wordC], path=/path/file-name.txt
```

**Comment by spyrosAv** [comment]
@acesar  When i try your command with the zk i am taking this message  :
```
Solr server not available on: http://127.0.1.1:9983/solr
Make sure that collection [spyros44] exists
```

![solr](https://cloud.githubusercontent.com/assets/20105756/18731484/d82e8178-8064-11e6-9448-b46fdc8e5cfe.png)

when i use `-s http://127.0.1.1:8983/solr` everything runs fine, but no data is sent to Solr...
I create the collections with this: `bin/solr -e cloud`
Any ideas?

**Comment by acesar** [comment]
@spyrosAv `-zk` is for the zookeeper String, your port is `9983`.

> everything runs fine, but no data is sent to Solr...

Can you share the output of the job?
do you have a field name `path` in your Solr Schema?

**Comment by spyrosAv** [comment]
@acesar   I have the field `path` at my schema
 Whit this : 
`-zk http://127.0.1.1:9983/solr `
![solr1](https://cloud.githubusercontent.com/assets/20105756/18732067/f8a41478-8068-11e6-93c7-68b113de2a30.png)
![sol2](https://cloud.githubusercontent.com/assets/20105756/18732071/fec8e428-8068-11e6-83f0-919112a36e30.png)

whit this : 
`-s http://127.0.1.1:8983/solr`
![solr4](https://cloud.githubusercontent.com/assets/20105756/18732117/782b23a8-8069-11e6-8947-84e8d53eea10.png)

![solr5](https://cloud.githubusercontent.com/assets/20105756/18732118/7af74a12-8069-11e6-8e0b-3b86110757fd.png)

**Comment by acesar** [comment]
@spyrosAv 
> -zk http://127.0.1.1:9983/solr

The zk string should be `-zk 127.0.1.1:9983` but if you only have one Solr node. It should be the same as the `-s` option.

The output seems to be correct.

it has a `DOCS_ADDED` value of `12761`, you should have  those docs in Solr.

Go to `http://127.0.1.1:8983/solr` and look at the collection.

**Comment by spyrosAv** [comment]
In this case i have 2 nodes. But i have tried with 1 also.
Looking for "book" word 
![quer1](https://cloud.githubusercontent.com/assets/20105756/18732522/85db4390-806c-11e6-8aff-d0416bd8312c.png)

**Comment by acesar** [comment]
@spyrosAv  Can you try again with the field `match_ss`?

     hadoop jar solr-hadoop-job-2.2.5.jar com.lucidworks.hadoop.ingest.IngestJob  
        -Dlww.commit.on.close=true 
        -Dcom.lucidworks.hadoop.ingest.RegexIngestMapper.regex="\\w+" 
       -Dcom.lucidworks.hadoop.ingest.RegexIngestMapper.groups_to_fields=0=match_ss  
       -cls com.lucidworks.hadoop.ingest.RegexIngestMapper  
       -c collection1 -i /path/* -zk 127.0.0.1: 9983
       -of com.lucidworks.hadoop.io.LWMapRedOutputFormat 


Can you first search with the `*:*` value to see how many docs you have.

The next step should be to search with `match_ss:book`

**Comment by spyrosAv** [comment]
@acesar `match_ss` worked!!!
Thanks for the help and the your time!!!

**Comment by acesar** [comment]
Sure np!

**Comment by spyrosAv** [comment]
@acesar If you could provide some information why `match_ss` worked and `match_s` didn't, i would appreciate it.

**Comment by acesar** [comment]
@spyrosAv The` RegexIngestMapper` add the matches from the regex to an Array of values (multivalue in Solr).  A Dynamic multivalue in Solr has the suffix  `_ss` by default.

**Comment by spyrosAv** [comment]
@acesar  Which Ingest Mapper should i use if i am using .pdf or .doc files? Is GrokIngestMapper the right one ?  
Also is there any documentation about the project that will help me figure out queries like this?
Thanks in advance.
(I am not opening a new issue but if you feel is needed just tell me...)
