### ISSUE TITLE
DirectoryIngestMapper index documents by filetype

### ISSUE THREAD

**Issue by acesar** [lucidworks/hadoop-solr#17]
From [stackoverflow](http://stackoverflow.com/questions/39377140/mapreduceindexertool-best-way-to-index-hdfs-files-in-solr/39627854#39627854)

> I have a requirement where I have to index HDFS files (includes TXT, PDF, DOCX, other rich documents) into Solr.
> 
> Currently, I am using DirectoryIngestMapper of the LucidWorks connector to achieve the same. https://github.com/lucidworks/hadoop-solr
> 
> But I cannot work with this because it has certain limitations (the main one being that you cannot specify the filetypes to be considered).

The `DirectoryIngestMapper` can index only one type of documents adding the file extension at the end of the path `-i /path/*.pdf`, However, I does not work recursively with subdirectories  `-Dadd.subdirectories=true` 

For subdirectories is adding `"/*"` to the paths [Source](https://github.com/lucidworks/hadoop-solr/blob/master/solr-hadoop-core/src/main/java/com/lucidworks/hadoop/ingest/DirectoryIngestMapper.java#L92)
`new Path(fstat.getPath().toUri().toString() + "/*"));`

**Comment by Git-Boy** [comment]
I have noticed another similar problem.

Suppose I have a directory structure like this:
`/directory/sub1/`
Let the imaginary `sub1` folder contain some files to be indexed.

If I give `-i /directory/*`, nothing gets indexed. Indexing happens only when the parameter is `-i /directory/sub1/*`. That is, the subdirectory crawling does not take place. This issue is not there with every subdirectory, but many of them. I don't know what's wrong since it seems to be very random.

**Comment by acesar** [comment]
@Git-Boy 
> If I give -i /directory/*, nothing gets indexed

Did you use `-Dadd.subdirectories=true` argument?

**Comment by Git-Boy** [comment]
Yes, I had used the argument. The main directory had a lot of subdirectories. The files from certain subdirectories were getting indexed while most were not. I could not explain this strange behavior.

Finally, had to work around the problem by doing MapReduce jobs for each subdirectory
(There were around 1000 subdirectories).

**Comment by acesar** [comment]
@Git-Boy It seems to be a memory issue with that many subfolders.

I suggest that you make an script to create the hadoop command for each subfolder. (it seems that you took a similar approach)

**Comment by Git-Boy** [comment]
@acesar 

I did some experiments to test the sub-folder crawling behaviour of the command. I created some sample folders with the following hierarchy, `/folder1/folder2`. `folder2` contains many PDF documents.

But when I run the command from `folder1`, none of the files get indexed.

**Comment by Git-Boy** [comment]
It still doesn't completely explain the behaviour.

When I was done with the first run, just 600 (approx.) files were indexed out of more than 10000.
:(

That's very low.

**Comment by acesar** [comment]
@Git-Boy Can you share the command used?
Did the job finished with errors? 
Can you share solr/hadoop logs?
