### ISSUE TITLE
Wrong split key in IngestJob.java

### ISSUE THREAD

**Issue by jstraub-hw** [LucidWorks/hadoop-solr#2]
Additional configurations can be passed to an Hadoop/Solr-Ingestion Job via _"--conf"_
For example: `hadoop-job.jar --collection test ... --conf key1=value1;key2=value2 `
These additional configurations are processed by the class _IngestJob.java_ (hadoop-solr/solr-hadoop-core/src/main/java/com/lucidworks/hadoop/ingest/IngestJob.java) and the method _processConf(...)_

Test 1: Config =  `--conf mapreduce.task.timeout=0`
Result 1: "cant parse split: mapreduce.task.timeout="

Test 2: Config = `--conf mapreduce.tar.timeout[0`
Result 2: Job will be started

I believe the error comes from these lines
Line 254/255:
```
//split on =, LHS is the key, RHS is the value, as a single value
String[] keyVal = split.split("\\[");
```
The method is supposed to split additional job configurations by "=", but instead its using "[" as split character.

**Comment by acesar** [comment]
The description of the `--conf` argument is misleading.
 The format of the conf is:`--conf csvFieldMapping[0=bar, 1=id, 2=junk , 3 = zen ,4 = hockey];idField[junk]`

[See https://github.com/LucidWorks/hadoop-solr/blob/master/solr-hadoop-core/src/test/java/com/lucidworks/hadoop/ingest/IngestJobTest.java#L52]

I fixed the description, closing.
