### ISSUE TITLE
csv file split by tab

### ISSUE THREAD

**Issue by benchuang11046** [lucidworks/hadoop-solr#7]
Hello
I index for a csv file split by tab(\t).
However, the parameter -DcsvDelimiter only takes the first char.
Do you will support index split by tab(\t)?

Thanks

**Comment by acesar** [comment]
> Do you will support index split by tab(\t)?

@benchuang11046 yes, it is supported.
You need to specify the csv strategy with `-DcsvStrategy=tdf`.  (tdf is for a csv file split by tab).

**Comment by benchuang11046** [comment]
Thanks! 
It works well.
